import 'package:intl/intl.dart';
import 'package:jiffy/jiffy.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserChatListResultChatsLastMessageSender {
/*
{
  "_id": "6315e547fa9cb80348b74a7c",
  "fullname": "Ashish ",
  "profile": null
}
*/

  String? Id;
  String? fullname;
  String? profile;

  UserChatListResultChatsLastMessageSender({
    this.Id,
    this.fullname,
    this.profile,
  });
  UserChatListResultChatsLastMessageSender.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    fullname = json['fullname']?.toString();
    profile = json['profile']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['fullname'] = fullname;
    data['profile'] = profile;
    return data;
  }
}

class UserChatListResultChatsLastMessageBody {
/*
{
  "type": "message",
  "message": "Hi man ",
  "media": [
    null
  ]
}
*/

  String? type;
  String? message;


  UserChatListResultChatsLastMessageBody({
    this.type,
    this.message,
  });
  UserChatListResultChatsLastMessageBody.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    message = json['message']?.toString();

    }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['message'] = message;
    return data;
  }
}

class UserChatListResultChatsLastMessage {
/*
{
  "_id": "636cbde713c54f18e3e36567",
  "body": {
    "type": "message",
    "message": "Hi man ",
    "media": [
      null
    ]
  },
  "quote": null,
  "chatId": "63380e996ff3727329ba98c7",
  "tags": [
    null
  ],
  "createdAt": "2022-11-10T09:01:27.844Z",
  "updatedAt": "2022-11-10T09:01:27.844Z",
  "sender": [
    {
      "_id": "6315e547fa9cb80348b74a7c",
      "fullname": "Ashish ",
      "profile": null
    }
  ]
}
*/

  String? Id;
  UserChatListResultChatsLastMessageBody? body;
  String? quote;
  String? chatId;
  String? timeStamp;
  String? time;
  String? createdAt;
  String? updatedAt;
  List<UserChatListResultChatsLastMessageSender?>? sender;

  UserChatListResultChatsLastMessage({
    this.Id,
    this.body,
    this.quote,
    this.chatId,
    this.createdAt,
    this.updatedAt,
    this.timeStamp,
    this.time,
    this.sender,
  });
  String get caldate {
    String dateTime = DateFormat("EEE dd MMM yy").format(DateTime.parse(createdAt!));
    String today = DateFormat("EEE dd MMM yy").format(DateTime.now());
    return dateTime == today ?"Today":dateTime;
  }
  String get caltime {
    String time = Jiffy(createdAt!).Hm;
    return time;
  }
  UserChatListResultChatsLastMessage.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    body = (json['body'] != null) ? UserChatListResultChatsLastMessageBody.fromJson(json['body']) : null;
    quote = json['quote']?.toString();
    chatId = json['chatId']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    if (json['sender'] != null) {
    final v = json['sender'];
    final arr0 = <UserChatListResultChatsLastMessageSender>[];
    v.forEach((v) {
    arr0.add(UserChatListResultChatsLastMessageSender.fromJson(v));
    });
    sender = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    if (body != null) {
      data['body'] = body!.toJson();
    }
    data['quote'] = quote;
    data['chatId'] = chatId;

    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (sender != null) {
    final v = sender;
    final arr0 = [];
    v!.forEach((v) {
    arr0.add(v!.toJson());
    });
    data['sender'] = arr0;
    }
    return data;
  }
}

class UserChatListResultChatsChatDetailsUserDetails {
/*
{
  "_id": "6336a21cb552d25ee12434f4",
  "fullname": "Abhishek Kumar",
  "profile": "1664526575732.jpg"
}
*/

  String? Id;
  String? fullname;
  String? profile;

  UserChatListResultChatsChatDetailsUserDetails({
    this.Id,
    this.fullname,
    this.profile,
  });
  UserChatListResultChatsChatDetailsUserDetails.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    fullname = json['fullname']?.toString();
    profile = json['profile']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['fullname'] = fullname;
    data['profile'] = profile;
    return data;
  }
}

class UserChatListResultChatsChatDetails {
/*
{
  "_id": "63380e996ff3727329ba98c7",
  "title": null,
  "isGroup": false,
  "category": "conversation",
  "isClosed": false,
  "muddaId": null,
  "orgId": null,
  "groupLimit": 0,
  "icon": "",
  "createdAt": "2022-09-14T06:06:20.061Z",
  "updatedAt": "2022-09-14T06:06:20.061Z",
  "userDetails": {
    "_id": "6336a21cb552d25ee12434f4",
    "fullname": "Abhishek Kumar",
    "profile": "1664526575732.jpg"
  }
}
*/

  String? Id;
  String? title;
  bool? isGroup;
  String? category;
  bool? isClosed;
  String? muddaId;
  String? orgId;
  int? groupLimit;
  String? icon;
  String? muddaCat;
  String? createdAt;
  String? updatedAt;
  UserChatListResultChatsChatDetailsUserDetails? userDetails;
  bool? isUserBlocked;


  UserChatListResultChatsChatDetails({
    this.Id,
    this.title,
    this.isGroup,
    this.category,
    this.isClosed,
    this.muddaId,
    this.orgId,
    this.groupLimit,
    this.icon,
    this.muddaCat,
    this.createdAt,
    this.updatedAt,
    this.userDetails,
    this.isUserBlocked,
  });
  UserChatListResultChatsChatDetails.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    isGroup = json['isGroup'];
    category = json['category']?.toString();
    isClosed = json['isClosed'];
    muddaId = json['muddaId']?.toString();
    orgId = json['orgId']?.toString();
    groupLimit = json['groupLimit']?.toInt();
    icon = json['icon']?.toString();
    muddaCat = json['muddaCat']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    userDetails = (json['userDetails'] != null) ? UserChatListResultChatsChatDetailsUserDetails.fromJson(json['userDetails']) : null;
    isUserBlocked = json['isUserBlocked'] ?? false;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['isGroup'] = isGroup;
    data['category'] = category;
    data['isClosed'] = isClosed;
    data['muddaId'] = muddaId;
    data['orgId'] = orgId;
    data['groupLimit'] = groupLimit;
    data['icon'] = icon;
    data['muddaCat'] = muddaCat;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (userDetails != null) {
      data['userDetails'] = userDetails!.toJson();
    }
    data['isUserBlocked'] = isUserBlocked;
    return data;
  }
}

class UserChatListResultChats {


  String? Id;
  String? chatId;
  String? userId;
  String? role;
  String? joinDate;
  String? createdAt;
  String? updatedAt;
  List<UserChatListResultChatsChatDetails>? chatDetails;
  String? muddaThumbnail;
  String? orgThumbnail;
  int? orgMemberCount;
  int? favourCount;
  int? oppositionCount;
  bool isNewMessage=false;
  UserChatListResultChatsLastMessage? lastMessage;


  UserChatListResultChats({
    this.Id,
    this.chatId,
    this.userId,
    this.role,
    this.joinDate,
    this.createdAt,
    this.updatedAt,
    this.chatDetails,
    this.muddaThumbnail,
    this.orgThumbnail,
    this.orgMemberCount,
    this.favourCount,
    this.oppositionCount,
    this.isNewMessage=false,
    this.lastMessage,
  });
  UserChatListResultChats.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    chatId = json['chatId']?.toString();
    userId = json['userId']?.toString();
    role = json['role']?.toString();
    joinDate = json['joinDate']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    if (json['chatDetails'] != null) {
      final v = json['chatDetails'];
      final arr0 = <UserChatListResultChatsChatDetails>[];
      v.forEach((v) {
        arr0.add(UserChatListResultChatsChatDetails.fromJson(v));
      });
      chatDetails = arr0;
    }
    muddaThumbnail = json['muddaThumbnail']?.toString();
    orgThumbnail = json['orgThumbnail']?.toString();
    orgMemberCount = json['orgMemberCount']?.toInt();
    favourCount = json['favourCount']?.toInt();
    oppositionCount = json['oppositionCount']?.toInt();
    lastMessage = (json['lastMessage'] != null) ? UserChatListResultChatsLastMessage.fromJson(json['lastMessage']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['chatId'] = chatId;
    data['userId'] = userId;
    data['role'] = role;
    data['joinDate'] = joinDate;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (chatDetails != null) {
      final v = chatDetails;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data['chatDetails'] = arr0;
    }
    data['muddaThumbnail'] = muddaThumbnail;
    data['orgThumbnail'] = orgThumbnail;
    data['orgMemberCount'] = orgMemberCount;
    data['favourCount'] = favourCount;
    data['oppositionCount'] = oppositionCount;
    if (lastMessage != null) {
      data['lastMessage'] = lastMessage!.toJson();
    }
    return data;
  }
}

class UserChatListResult {
/*
{
  "chats": [
    {
      "_id": "63399c6abd288d5a954797e8",
      "chatId": "63380e996ff3727329ba98c7",
      "userId": "6315e547fa9cb80348b74a7c",
      "role": "member",
      "joinDate": "2022-10-01T06:06:20.112Z",
      "createdAt": "2022-10-01T06:06:20.112Z",
      "updatedAt": "2022-10-01T06:06:20.112Z",
      "chatDetails": [
        {
          "_id": "63380e996ff3727329ba98c7",
          "title": null,
          "isGroup": false,
          "category": "conversation",
          "isClosed": false,
          "muddaId": null,
          "orgId": null,
          "groupLimit": 0,
          "icon": "",
          "createdAt": "2022-09-14T06:06:20.061Z",
          "updatedAt": "2022-09-14T06:06:20.061Z",
          "userDetails": {
            "_id": "6336a21cb552d25ee12434f4",
            "fullname": "Abhishek Kumar",
            "profile": "1664526575732.jpg"
          }
        }
      ],
      "lastMessage": {
        "_id": "636cbde713c54f18e3e36567",
        "body": {
          "type": "message",
          "message": "Hi man ",
          "media": [
            null
          ]
        },
        "quote": null,
        "chatId": "63380e996ff3727329ba98c7",
        "tags": [
          null
        ],
        "createdAt": "2022-11-10T09:01:27.844Z",
        "updatedAt": "2022-11-10T09:01:27.844Z",
        "sender": [
          {
            "_id": "6315e547fa9cb80348b74a7c",
            "fullname": "Ashish ",
            "profile": null
          }
        ]
      }
    }
  ]
}
*/

  List<UserChatListResultChats>? chats;

  UserChatListResult({
    this.chats,
  });
  UserChatListResult.fromJson(Map<String, dynamic> json) {
    if (json['chats'] != null) {
      final v = json['chats'];
      final arr0 = <UserChatListResultChats>[];
      v.forEach((v) {
        arr0.add(UserChatListResultChats.fromJson(v));
      });
      chats = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (chats != null) {
      final v = chats;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data['chats'] = arr0;
    }
    return data;
  }
}

class UserChatList {


  UserChatListResult? result;
  String? message;
  bool? success;
  bool? fromCache;
  bool? notifications;
  int? status;

  UserChatList({
    this.result,
    this.message,
    this.success,
    this.status,
    this.fromCache,
    this.notifications
  });
  UserChatList.fromJson(Map<dynamic, dynamic> json) {
    result = (json['result'] != null) ? UserChatListResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    success = json['success'];
    if(json['notifications']!=null){
      notifications = json['notifications'];
    }

    status = json['status']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['success'] = success;
    if(notifications !=null){
      data['notifications'] = notifications;
    }
    data['status'] = status;
    return data;
  }
}
