///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MuddaDetailsDataGallery {
/*
{
  "_id": "6312ff04dc5a91a041e42626",
  "user_id": "62e4cd4531a1f86907c51393",
  "relative_id": "6312ff04dc5a91a041e42622",
  "relative_type": "RealMudda",
  "file": "1662189312682.jpg",
  "path": "uploads/mudda/",
  "status": 1,
  "created_by": null,
  "updated_by": null,
  "deleted": false,
  "createdAt": "2022-09-03T07:15:16.324Z",
  "updatedAt": "2022-09-03T07:15:16.324Z",
  "__v": 0
}
*/

  String? Id;
  String? userId;
  String? relativeId;
  String? relativeType;
  String? file;
  String? path;
  int? status;
  String? createdBy;
  String? updatedBy;
  bool? deleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  MuddaDetailsDataGallery({
    this.Id,
    this.userId,
    this.relativeId,
    this.relativeType,
    this.file,
    this.path,
    this.status,
    this.createdBy,
    this.updatedBy,
    this.deleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  MuddaDetailsDataGallery.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    userId = json['user_id']?.toString();
    relativeId = json['relative_id']?.toString();
    relativeType = json['relative_type']?.toString();
    file = json['file']?.toString();
    path = json['path']?.toString();
    status = json['status']?.toInt();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    deleted = json['deleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['user_id'] = userId;
    data['relative_id'] = relativeId;
    data['relative_type'] = relativeType;
    data['file'] = file;
    data['path'] = path;
    data['status'] = status;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    data['deleted'] = deleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class MuddaDetailsData {
/*
{
  "rejectedBy": null,
  "approvedDate": null,
  "rejectedDate": null,
  "_id": "6312ff04dc5a91a041e42622",
  "user_id": "62e4cd4531a1f86907c51393",
  "post_as": "user",
  "thumbnail": "1662189312656.jpg",
  "title": "Pesticides should be banned",
  "initial_scope": "district",
  "mudda_description": "Pesticides are the reason for modern diseases.\n\nLet's join hand to protest the ban on them \n\nModern diseases: Cancer, blood vessels blockages, skin related\n\nThese people won't care about your health. But we do care about it. So I hope you would wan to take care of your upcoming generation. Thanks ",
  "hashtags": [
    "Health"
  ],
  "area": null,
  "landmark": null,
  "city": "mumbai",
  "state": "maharashtra",
  "country": "india",
  "zipcode": null,
  "latitude": null,
  "longitude": null,
  "audience_gender": "both",
  "audience_age": "All",
  "isVerify": 1,
  "verify_by": null,
  "status": 1,
  "created_by": null,
  "updated_by": null,
  "deleted": false,
  "createdAt": "2022-09-03T07:15:16.297Z",
  "updatedAt": "2022-10-20T07:59:59.332Z",
  "__v": 0,
  "postApprovals": "all",
  "isArchived": false,
  "joinApprovals": "admin",
  "gallery": [
    {
      "_id": "6312ff04dc5a91a041e42626",
      "user_id": "62e4cd4531a1f86907c51393",
      "relative_id": "6312ff04dc5a91a041e42622",
      "relative_type": "RealMudda",
      "file": "1662189312682.jpg",
      "path": "uploads/mudda/",
      "status": 1,
      "created_by": null,
      "updated_by": null,
      "deleted": false,
      "createdAt": "2022-09-03T07:15:16.324Z",
      "updatedAt": "2022-09-03T07:15:16.324Z",
      "__v": 0
    }
  ],
  "id": "6312ff04dc5a91a041e42622"
}
*/

  String? rejectedBy;
  String? approvedDate;
  String? rejectedDate;
  String? Id;
  String? userId;
  String? postAs;
  String? thumbnail;
  String? title;
  String? initialScope;
  String? muddaDescription;
  List<String?>? hashtags;
  String? area;
  String? landmark;
  String? city;
  String? state;
  String? country;
  String? zipcode;
  String? latitude;
  String? longitude;
  String? audienceGender;
  String? audienceAge;
  int? isVerify;
  String? verifyBy;
  int? status;
  String? createdBy;
  String? updatedBy;
  bool? deleted;
  String? createdAt;
  String? updatedAt;
  int? V;
  String? postApprovals;
  bool? isArchived;
  String? joinApprovals;
  List<MuddaDetailsDataGallery?>? gallery;
  String? id;

  MuddaDetailsData({
    this.rejectedBy,
    this.approvedDate,
    this.rejectedDate,
    this.Id,
    this.userId,
    this.postAs,
    this.thumbnail,
    this.title,
    this.initialScope,
    this.muddaDescription,
    this.hashtags,
    this.area,
    this.landmark,
    this.city,
    this.state,
    this.country,
    this.zipcode,
    this.latitude,
    this.longitude,
    this.audienceGender,
    this.audienceAge,
    this.isVerify,
    this.verifyBy,
    this.status,
    this.createdBy,
    this.updatedBy,
    this.deleted,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.postApprovals,
    this.isArchived,
    this.joinApprovals,
    this.gallery,
    this.id,
  });
  MuddaDetailsData.fromJson(Map<String, dynamic> json) {
    rejectedBy = json['rejectedBy']?.toString();
    approvedDate = json['approvedDate']?.toString();
    rejectedDate = json['rejectedDate']?.toString();
    Id = json['_id']?.toString();
    userId = json['user_id']?.toString();
    postAs = json['post_as']?.toString();
    thumbnail = json['thumbnail']?.toString();
    title = json['title']?.toString();
    initialScope = json['initial_scope']?.toString();
    muddaDescription = json['mudda_description']?.toString();
    if (json['hashtags'] != null) {
      final v = json['hashtags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      hashtags = arr0;
    }
    area = json['area']?.toString();
    landmark = json['landmark']?.toString();
    city = json['city']?.toString();
    state = json['state']?.toString();
    country = json['country']?.toString();
    zipcode = json['zipcode']?.toString();
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    audienceGender = json['audience_gender']?.toString();
    audienceAge = json['audience_age']?.toString();
    isVerify = json['isVerify']?.toInt();
    verifyBy = json['verify_by']?.toString();
    status = json['status']?.toInt();
    createdBy = json['created_by']?.toString();
    updatedBy = json['updated_by']?.toString();
    deleted = json['deleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    postApprovals = json['postApprovals']?.toString();
    isArchived = json['isArchived'];
    joinApprovals = json['joinApprovals']?.toString();
    if (json['gallery'] != null) {
      final v = json['gallery'];
      final arr0 = <MuddaDetailsDataGallery>[];
      v.forEach((v) {
        arr0.add(MuddaDetailsDataGallery.fromJson(v));
      });
      gallery = arr0;
    }
    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rejectedBy'] = rejectedBy;
    data['approvedDate'] = approvedDate;
    data['rejectedDate'] = rejectedDate;
    data['_id'] = Id;
    data['user_id'] = userId;
    data['post_as'] = postAs;
    data['thumbnail'] = thumbnail;
    data['title'] = title;
    data['initial_scope'] = initialScope;
    data['mudda_description'] = muddaDescription;
    if (hashtags != null) {
      final v = hashtags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['hashtags'] = arr0;
    }
    data['area'] = area;
    data['landmark'] = landmark;
    data['city'] = city;
    data['state'] = state;
    data['country'] = country;
    data['zipcode'] = zipcode;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['audience_gender'] = audienceGender;
    data['audience_age'] = audienceAge;
    data['isVerify'] = isVerify;
    data['verify_by'] = verifyBy;
    data['status'] = status;
    data['created_by'] = createdBy;
    data['updated_by'] = updatedBy;
    data['deleted'] = deleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    data['postApprovals'] = postApprovals;
    data['isArchived'] = isArchived;
    data['joinApprovals'] = joinApprovals;
    if (gallery != null) {
      final v = gallery;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['gallery'] = arr0;
    }
    data['id'] = id;
    return data;
  }
}

class MuddaDetails {
/*
{
  "status": 1,
  "message": "Get data Successfully",
  "data": {
    "rejectedBy": null,
    "approvedDate": null,
    "rejectedDate": null,
    "_id": "6312ff04dc5a91a041e42622",
    "user_id": "62e4cd4531a1f86907c51393",
    "post_as": "user",
    "thumbnail": "1662189312656.jpg",
    "title": "Pesticides should be banned",
    "initial_scope": "district",
    "mudda_description": "Pesticides are the reason for modern diseases.\n\nLet's join hand to protest the ban on them \n\nModern diseases: Cancer, blood vessels blockages, skin related\n\nThese people won't care about your health. But we do care about it. So I hope you would wan to take care of your upcoming generation. Thanks ",
    "hashtags": [
      "Health"
    ],
    "area": null,
    "landmark": null,
    "city": "mumbai",
    "state": "maharashtra",
    "country": "india",
    "zipcode": null,
    "latitude": null,
    "longitude": null,
    "audience_gender": "both",
    "audience_age": "All",
    "isVerify": 1,
    "verify_by": null,
    "status": 1,
    "created_by": null,
    "updated_by": null,
    "deleted": false,
    "createdAt": "2022-09-03T07:15:16.297Z",
    "updatedAt": "2022-10-20T07:59:59.332Z",
    "__v": 0,
    "postApprovals": "all",
    "isArchived": false,
    "joinApprovals": "admin",
    "gallery": [
      {
        "_id": "6312ff04dc5a91a041e42626",
        "user_id": "62e4cd4531a1f86907c51393",
        "relative_id": "6312ff04dc5a91a041e42622",
        "relative_type": "RealMudda",
        "file": "1662189312682.jpg",
        "path": "uploads/mudda/",
        "status": 1,
        "created_by": null,
        "updated_by": null,
        "deleted": false,
        "createdAt": "2022-09-03T07:15:16.324Z",
        "updatedAt": "2022-09-03T07:15:16.324Z",
        "__v": 0
      }
    ],
    "id": "6312ff04dc5a91a041e42622"
  },
  "path": "https://mudda-dev.s3.ap-south-1.amazonaws.com/mudda/"
}
*/

  int? status;
  String? message;
  MuddaDetailsData? data;
  String? path;

  MuddaDetails({
    this.status,
    this.message,
    this.data,
    this.path,
  });
  MuddaDetails.fromJson(Map<dynamic, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? MuddaDetailsData.fromJson(json['data']) : null;
    path = json['path']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['path'] = path;
    return data;
  }
}
