///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UnapprovedMuddaCountResult {
/*
{
  "approved": 0,
  "underApproval": 14,
  "adminEdit": 1
}
*/

  int? approved;
  int? underApproval;
  int? adminEdit;

  UnapprovedMuddaCountResult({
    this.approved,
    this.underApproval,
    this.adminEdit,
  });
  UnapprovedMuddaCountResult.fromJson(Map<String, dynamic> json) {
    approved = json['approved']?.toInt();
    underApproval = json['underApproval']?.toInt();
    adminEdit = json['adminEdit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['approved'] = approved;
    data['underApproval'] = underApproval;
    data['adminEdit'] = adminEdit;
    return data;
  }
}

class UnapprovedMuddaCount {
/*
{
  "result": {
    "approved": 0,
    "underApproval": 14,
    "adminEdit": 1
  },
  "message": "Mudda counts fetched successfuly",
  "success": true,
  "status": 1
}
*/

  UnapprovedMuddaCountResult? result;
  String? message;
  bool? success;
  int? status;

  UnapprovedMuddaCount({
    this.result,
    this.message,
    this.success,
    this.status,
  });
  UnapprovedMuddaCount.fromJson(Map<dynamic, dynamic> json) {
    result = (json['result'] != null) ? UnapprovedMuddaCountResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    success = json['success'];
    status = json['status']?.toInt();
  }
  Map<dynamic, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['success'] = success;
    data['status'] = status;
    return data;
  }
}
